[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }
rand_xoshiro = "0.6.0"
rayon = "1.10.0"
